# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/kevoree_registry?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9300
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias kevoree_registry -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: kevoree_registry
# ===================================================================
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 1000 # Number of objects in each cache entry
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: registry@kevoree.org
        base-url: https://registry.kevoree.org # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: kevoree_registry
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:

#spring:
#    devtools:
#        restart:
#            enabled: false
#        livereload:
#            enabled: false
#    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:postgresql://localhost:5432/kevoree_registry
#        name: kevoree_registry
#        username: root
#        password: dummy
#    jpa:
#        database-platform: org.kevoree.registry.domain.util.FixedPostgreSQL82Dialect
#        database: POSTGRESQL
#        show-sql: false
#        properties:
#            hibernate.cache.use_second_level_cache: true
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: false
#            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
#            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
#            hibernate.cache.region.factory_class: org.kevoree.registry.config.jcache.SpringCacheRegionFactory
#    cache:
#        jcache:
#            config: ehcache.xml
#    mail:
#        host: localhost
#        port: 25
#        username:
#        password:
#    thymeleaf:
#        cache: true
#
#liquibase:
#    contexts: prod
#
#server:
#    port: 8080
#    compression:
#        enabled: true
#        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
#        min-response-size: 1024
#
## ===================================================================
## JHipster specific properties
## ===================================================================
#
#jhipster:
#    http:
#        cache: # Used by the CachingHttpHeadersFilter
#            timeToLiveInDays: 1461
#    cache: # Hibernate 2nd level cache, used by CacheConfiguration
#        ehcache:
#            maxBytesLocalHeap: 256M
#    mail: # specific JHipster mail property, for standard properties see MailProperties
#        from: contact@kevoree.org
#        baseUrl: https://registry.kevoree.org
#    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
#        jmx.enabled: true
#        graphite:
#            enabled: false
#            host: localhost
#            port: 2003
#            prefix: registry
#        prometheus:
#            enabled: false
#            endpoint: /prometheusMetrics
#        logs: # Reports Dropwizard metrics in the logs
#            enabled: false
#            reportFrequency: 60 # in seconds
#    logging:
#        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
#            enabled: false
#            host: localhost
#            port: 5000
#            queueSize: 512
